#!/bin/bash
SITE_ROOT=$(realpath $(dirname $(realpath $0))/..)
export HOME=$SITE_ROOT/tmp
. $SITE_ROOT/.env
ASDF=/massbit/massbitroute/app/gbc/bin/.asdf
GDNSD_VERSION=v3.8.0
GDNSD_DIR=$ASDF/installs/gdnsd/$GDNSD_VERSION
type=gwman
service_dir=/massbit/massbitroute/app/src/sites/services
cmd=$SITE_ROOT/cmd_server
cd $SITE_ROOT
_add_cron() {
	cat <<EOF >/tmp/crontab
0 0 * * * $SITE_ROOT/scripts/run _update_ssl
EOF
	crontab /tmp/crontab
}
_git_config() {
	git config --global user.name "Vu Tran"
	git config --global user.email "baysao@gmail.com"
}
_rebuild_conf() {
	_dir=$SITE_ROOT/data/zones
	_file_ok=$SITE_ROOT/zones/$DOMAIN
	_file=$(mktemp)
	cat $_dir/$DOMAIN >$_file
	echo >>$_file

	find $_dir/dapi -type f -iname '*.zone' | while read f; do
		cat $f >>$_file
		echo >>$_file
	done

	find $_dir/gateway -type f -iname '*.zone' | while read f; do
		cat $f >>$_file
		echo >>$_file
	done

	find $_dir/node -type f -iname '*.zone' | while read f; do
		cat $f >>$_file
		echo >>$_file
	done

	mv $_file $_file_ok
}
_reload() {
	#_update_ssl
	_rebuild_conf
	$GDNSD_DIR/sbin/gdnsd -c $SITE_ROOT checkconf
	if [ $? -eq 0 ]; then
		$GDNSD_DIR/bin/gdnsdctl -c $SITE_ROOT replace
	fi
	$cmd _update
}

_install() {
	mkdir -p $service_dir $SITE_ROOT/etc
	user=massbit
	pass=41d919e74993945a97972d147c4d01847e8bc1b6

	# git clone http://$user:$pass@git.massbitroute.com/massbitroute/${service}.git /massbit/massbitroute/app/$service
	# git -C /massbit/massbitroute/app/$service remote set-url origin http://$user:$pass@git.massbitroute.com/massbitroute/${service}.git

	service=gbc
	git clone http://$user:$pass@git.massbitroute.com/massbitroute/${service}.git /massbit/massbitroute/app/$service
	git -C /massbit/massbitroute/app/$service remote set-url origin http://$user:$pass@git.massbitroute.com/massbitroute/${service}.git

	service=asdf
	git clone http://$user:$pass@git.massbitroute.com/massbitroute/${service}.git /massbit/massbitroute/app/gbc/bin/.asdf

	git -C /massbit/massbitroute/app/gbc/bin/.asdf remote set-url origin http://$user:$pass@git.massbitroute.com/massbitroute/${service}.git

	service=mkagent
	git clone http://$user:$pass@git.massbitroute.com/massbitroute/${service}.git $SITE_ROOT/etc/$service

	git -C $SITE_ROOT/etc/$service remote set-url origin http://$user:$pass@git.massbitroute.com/massbitroute/${service}.git

	service=ssl
	user=$service
	pass=adf7caa9e1bbe306c31c98fdf690e9f645feee14
	git clone http://$user:$pass@git.massbitroute.com/massbitroute/${service}.git /etc/letsencrypt
	git -C /etc/letsencrypt remote set-url origin http://$user:$pass@git.massbitroute.com/massbitroute/${service}.git

	service=$type
	user=$service
	pass=067b14c85441fc9381d3425e1c9ed1dbc70017f2
	git clone http://$user:$pass@git.massbitroute.com/massbitroute/${service}.git $service_dir/$service
	git -C $service_dir/$service remote set-url origin http://$user:$pass@git.massbitroute.com/massbitroute/${service}.git

	ln -sf /massbit/massbitroute/app/gbc /massbit/massbitroute/app/src/gbc
	ln -sf /massbit/massbitroute/app/gbc/bin/openresty /usr/local/openresty
	apt-get update
	apt-get install -y git apache2-utils supervisor jq python-is-python2 libssl-dev \
		liburcu-dev libev-dev libsodium-dev libtool libunwind-dev libmaxminddb-dev

	cp supervisor.conf /etc/supervisor/conf.d/${type}.conf

	for svr in systemd-resolved; do
		systemctl disable $svr
		systemctl stop $svr
	done

	for svr in supervisor; do
		systemctl enable $svr
		systemctl start $svr
	done

	supervisorctl update
}

_update_ssl() {
	_git_config
	git_ssl='git -C /etc/letsencrypt'
	bash $SITE_ROOT/cert.sh _renew
	$git_ssl add /etc/letsencrypt
	$git_ssl commit -m update
	$git_ssl push origin master
}

_monitor() {
	_add_cron
	# renew ssl

	# check change on git
	is_reload=0
	git -C $SITE_ROOT pull origin master | grep -i "updating"
	if [ $? -eq 0 ]; then
		is_reload=1

	fi

	if [ $is_reload -ne 0 ]; then
		$0 _reload
	fi
}

_service_grafana() {
	mkdir -p $SITE_ROOT/data/grafana
	GRAFANA_DIR=$SITE_ROOT/bin/grafana/$GRAFANA_VERSION
	exec $GRAFANA_DIR/bin/grafana-server -config $SITE_ROOT/etc/grafana/stat.ini -homepath $GRAFANA_DIR
}

_service_prometheus() {
	mkdir -p $SITE_ROOT/data/prometheus
	PROMETHEUS_DIR=$SITE_ROOT/bin/prometheus/$PROMETHEUS_VERSION
	exec $PROMETHEUS_DIR/bin/prometheus --web.enable-admin-api --config.file=$SITE_ROOT/etc/prometheus/stat.yml --web.listen-address="127.0.0.1:44449" --web.external-url http://127.0.0.1:44449/__internal_prometheus --web.enable-lifecycle --storage.tsdb.path $SITE_ROOT/data/prometheus
}

_service_gdnsd() {
	# apt install -y liburcu-dev libev-dev libsodium-dev libtool libunwind-dev libmaxminddb-dev
	mkdir -p $SITE_ROOT/run/dns
	exec $GDNSD_DIR/sbin/gdnsd -c $SITE_ROOT -RD start
}
_run() {
	rm -rf $SITE_ROOT/tmp/*
	sleep 3
	$SITE_ROOT/start_server
}
loop() {
	while true; do
		$@
		sleep 3
	done

}
$@
